name: cunty
description: "A School Planer App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0

  logging: ^1.2.0
  go_router: ^13.0.1
  provider: ^6.0.0
  dynamic_color: ^1.6.8
  dio: ^5.4.1
  build_runner: ^2.4.8

  flutter_localizations:
    sdk: flutter
  # flutter_secure_storage: ^9.0.0
  uuid: ^4.3.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
