name: cunty
description: "A School Planer App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  # emoji_picker_flutter: ^1.6.3
  shared_preferences: ^2.2.2
  # socket_io_client: ^2.0.3+1
  # video_player: ^2.8.2
  google_fonts: ^6.1.0

  logging: ^1.2.0
  go_router: ^13.0.1
  # sqflite: ^2.3.0
  provider: ^6.0.0
  dynamic_color: ^1.6.8

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/sounds/
